# Generated by Django 4.2.13 on 2026-10-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('crisis', 'Crisis'), ('concern', 'Concern')], max_length=10)),
                ('trigger', models.CharField(choices=[('phrase', 'Phrase match'), ('model', 'Classifier')], max_length=10)),
                ('source', models.CharField(help_text='Endpoint that detected it.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'support_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('emergency', 'Emergency services'), ('hotline', 'Crisis hotline'), ('counselor', 'Therapist / counselor'), ('clinic', 'Clinic / hospital'), ('school', 'School guidance office')], default='hotline', max_length=20)),
                ('description', models.TextField(blank=True, help_text='One or two sentences shown under the name.')),
                ('phone', models.CharField(blank=True, help_text='Digits as they should be dialed, e.g. 1553 or 09175584673.', max_length=50)),
                ('sms', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('hours', models.CharField(blank=True, help_text='e.g. "24/7" or "Mon-Fri 8am-5pm".', max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('service_mode', models.CharField(choices=[('online', 'Online / phone'), ('in_person', 'In person'), ('both', 'Online and in person')], default='online', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('languages', models.CharField(blank=True, help_text='e.g. "English, Filipino".', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Only verified entries are shown. Verify by actually contacting the service.')),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Lower shows first.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_resources',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
