# Generated by Django 4.2.13 on 2026-10-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_deactivate_emergency_and_ncmh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'emotions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EmotionSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_links', to='api.emotion')),
            ],
            options={
                'db_table': 'emotion_songs',
                'ordering': ['emotion', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=300)),
                ('spotify_track_id', models.CharField(blank=True, max_length=64, null=True)),
                ('spotify_url', models.URLField(blank=True, null=True)),
                ('album', models.CharField(blank=True, max_length=300)),
                ('image', models.URLField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('emotions', models.ManyToManyField(related_name='songs', through='api.EmotionSong', to='api.emotion')),
            ],
            options={
                'db_table': 'songs',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='EmotionTrackPool',
        ),
        migrations.AddField(
            model_name='emotionsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_links', to='api.song'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('title', 'artist'), name='unique_song_title_artist'),
        ),
        migrations.AddConstraint(
            model_name='emotionsong',
            constraint=models.UniqueConstraint(fields=('emotion', 'song'), name='unique_emotion_song'),
        ),
    ]
