"""Seed the therapist-validated song collection.

Frozen copy of docs/music.md as approved on 2026-10-10: 13 emotions, 125
emotion-song pairings, 114 distinct songs (some songs are approved for more than
one emotion). Owner corrections the same day: Graduation March is by Holiday
Celebration Troupe, and "Innocence -- Hilder Svensson" is no longer approved for
Depressed. `position` is each song's place in its emotion's list, which is the
order the app shows.

Spotify IDs/URLs/artwork come from the offline resolution cache built before
this refactor (87 of 114 songs matched); a song with no match is still shown,
just not playable in-app. Do not parse docs/music.md here: a migration must
replay the same data forever. Change the collection with a new migration.
"""
from django.db import migrations

EMOTIONS = [('happy', 'Happy'),
 ('sad', 'Sad'),
 ('angry', 'Angry'),
 ('motivational', 'Motivated'),
 ('fear', 'Scared'),
 ('depressing', 'Depressed'),
 ('nostalgic', 'Nostalgic'),
 ('romantic', 'Romantic'),
 ('lonely', 'Lonely'),
 ('calm', 'Calm'),
 ('stressed', 'Stressed'),
 ('surprising', 'Surprised'),
 ('mixed', 'Mixed')]

SONGS = [{'title': 'Happy',
  'artist': 'Pharrell Williams',
  'spotify_track_id': '60nZcImufyMA1MKQY3dcCH',
  'spotify_url': 'https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH',
  'album': 'G I R L',
  'image': 'https://i.scdn.co/image/ab67616d0000b273e89d2c2a3db129062b3b4e4f',
  'duration_ms': 233306},
 {'title': "Can't Stop the Feeling!",
  'artist': 'Justin Timberlake',
  'spotify_track_id': '6JV2JOEocMgcZxYSZelKcc',
  'spotify_url': 'https://open.spotify.com/track/6JV2JOEocMgcZxYSZelKcc',
  'album': 'CAN\'T STOP THE FEELING! (from DreamWorks Animation\'s "TROLLS")',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ef37416970812293c08e8a78',
  'duration_ms': 236001},
 {'title': 'Best Day of My Life',
  'artist': 'American Authors',
  'spotify_track_id': '5Hroj5K7vLpIG4FNCRIjbP',
  'spotify_url': 'https://open.spotify.com/track/5Hroj5K7vLpIG4FNCRIjbP',
  'album': 'Oh, What A Life',
  'image': 'https://i.scdn.co/image/ab67616d0000b273cc761ba55b0e7abad4539abe',
  'duration_ms': 194240},
 {'title': 'Shake It Off',
  'artist': 'Taylor Swift',
  'spotify_track_id': '0cqRj7pUJDkTCEsJkx8snD',
  'spotify_url': 'https://open.spotify.com/track/0cqRj7pUJDkTCEsJkx8snD',
  'album': '1989 (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b27352b2a3824413eefe9e33817a',
  'duration_ms': 219200},
 {'title': 'Favorite Rings',
  'artist': 'Taylor Swift',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Salamin-Salamin',
  'artist': 'BINI',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Awitin Mo at Isasayaw Ko',
  'artist': 'VST & Company',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Walking on Sunshine',
  'artist': 'Katrina and the Waves',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': "Don't Stop Me Now",
  'artist': 'Queen',
  'spotify_track_id': '1NHWG8zxSEypSRF3UufrnO',
  'spotify_url': 'https://open.spotify.com/track/1NHWG8zxSEypSRF3UufrnO',
  'album': 'Jazz',
  'image': 'https://i.scdn.co/image/ab67616d0000b2736c03b757ece416e014feef5e',
  'duration_ms': 209413},
 {'title': 'Ligaya',
  'artist': 'Eraserheads',
  'spotify_track_id': '5Ro6MdZGgce4PEuaFCJYPq',
  'spotify_url': 'https://open.spotify.com/track/5Ro6MdZGgce4PEuaFCJYPq',
  'album': 'Ultraelectromagneticpop!',
  'image': 'https://i.scdn.co/image/ab67616d0000b2739e54b097496758fd33c2b9dc',
  'duration_ms': 269733},
 {'title': 'Fix You',
  'artist': 'Coldplay',
  'spotify_track_id': '7LVHVU3tWfcxj5aiPFEW4Q',
  'spotify_url': 'https://open.spotify.com/track/7LVHVU3tWfcxj5aiPFEW4Q',
  'album': 'X&Y',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734e0362c225863f6ae2432651',
  'duration_ms': 295533},
 {'title': 'Before It Sinks In',
  'artist': 'Moira Dela Torre',
  'spotify_track_id': '59L27mlziC9IxqrvThBTMs',
  'spotify_url': 'https://open.spotify.com/track/59L27mlziC9IxqrvThBTMs',
  'album': 'Malaya',
  'image': 'https://i.scdn.co/image/ab67616d0000b27369dcb3f892ec9c2e2d81d3dc',
  'duration_ms': 263720},
 {'title': 'Happier',
  'artist': 'Ed Sheeran',
  'spotify_track_id': '2RttW7RAu5nOAfq6YFvApB',
  'spotify_url': 'https://open.spotify.com/track/2RttW7RAu5nOAfq6YFvApB',
  'album': '÷ (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96',
  'duration_ms': 207520},
 {'title': 'The Night We Met',
  'artist': 'Lord Huron',
  'spotify_track_id': '5yJaXWIErrrsjQ3J0eR5aK',
  'spotify_url': 'https://open.spotify.com/track/5yJaXWIErrrsjQ3J0eR5aK',
  'album': 'Strange Trails',
  'image': 'https://i.scdn.co/image/ab67616d0000b273b4916183f769aca218acb85f',
  'duration_ms': 208226},
 {'title': '12:51',
  'artist': 'Krissy & Ericka',
  'spotify_track_id': '1FHCU1rDAeaPsBW9byjJ0Q',
  'spotify_url': 'https://open.spotify.com/track/1FHCU1rDAeaPsBW9byjJ0Q',
  'album': 'Twelve: Fifty One (International Version)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ea1eb0d124f485d312b89b21',
  'duration_ms': 246280},
 {'title': 'Huling Sandali',
  'artist': 'December Avenue',
  'spotify_track_id': '6rIx9meOtOHDoo6ryRUdHv',
  'spotify_url': 'https://open.spotify.com/track/6rIx9meOtOHDoo6ryRUdHv',
  'album': 'Langit Mong Bughaw',
  'image': 'https://i.scdn.co/image/ab67616d0000b273d24f561dcce1e3ad344d1597',
  'duration_ms': 343017},
 {'title': "You'll Be in My Heart",
  'artist': 'NIKI',
  'spotify_track_id': '1UPB5rYJ0bzn6mNSoAHrZC',
  'spotify_url': 'https://open.spotify.com/track/1UPB5rYJ0bzn6mNSoAHrZC',
  'album': "You'll Be In My Heart",
  'image': 'https://i.scdn.co/image/ab67616d0000b2737cd329ea4a204a8a47caf3d5',
  'duration_ms': 241776},
 {'title': 'Let Her Go',
  'artist': 'Passenger',
  'spotify_track_id': '0eBaGW45Jk8r5SD2ODlUqE',
  'spotify_url': 'https://open.spotify.com/track/0eBaGW45Jk8r5SD2ODlUqE',
  'album': 'Let Her Go (Acoustic Version)',
  'image': 'https://i.scdn.co/image/ab67616d0000b27372eacedfe3815c988c46efd4',
  'duration_ms': 239229},
 {'title': 'Blue',
  'artist': 'Yung Kai',
  'spotify_track_id': '3be9ACTxtcL6Zm4vJRUiPG',
  'spotify_url': 'https://open.spotify.com/track/3be9ACTxtcL6Zm4vJRUiPG',
  'album': 'blue',
  'image': 'https://i.scdn.co/image/ab67616d0000b273e3c060bdd41fed06a866c494',
  'duration_ms': 214357},
 {'title': '21 Guns',
  'artist': 'Green Day',
  'spotify_track_id': '64yrDBpcdwEdNY9loyEGbX',
  'spotify_url': 'https://open.spotify.com/track/64yrDBpcdwEdNY9loyEGbX',
  'album': '21st Century Breakdown',
  'image': 'https://i.scdn.co/image/ab67616d0000b273c2ced39899b0d67cd5a724fa',
  'duration_ms': 321093},
 {'title': 'Look What You Made Me Do',
  'artist': 'Taylor Swift',
  'spotify_track_id': '1P17dC1amhFzptugyAO7Il',
  'spotify_url': 'https://open.spotify.com/track/1P17dC1amhFzptugyAO7Il',
  'album': 'reputation',
  'image': 'https://i.scdn.co/image/ab67616d0000b273da5d5aeeabacacc1263c0f4b',
  'duration_ms': 211853},
 {'title': 'Nosi Ba Lasi',
  'artist': 'Sampaguita',
  'spotify_track_id': '2DYuRUD7jYCxQXnv8Kmciz',
  'spotify_url': 'https://open.spotify.com/track/2DYuRUD7jYCxQXnv8Kmciz',
  'album': 'Nosi Ba Lasi',
  'image': 'https://i.scdn.co/image/ab67616d0000b27341dae1830ed63633da02b2ab',
  'duration_ms': 258573},
 {'title': 'Cool Off',
  'artist': 'Yeng Constantino',
  'spotify_track_id': '7MamPMGJwlY62QyC9M5esV',
  'spotify_url': 'https://open.spotify.com/track/7MamPMGJwlY62QyC9M5esV',
  'album': 'Salamat',
  'image': 'https://i.scdn.co/image/ab67616d0000b2736edba5a2524763e64e97d9a4',
  'duration_ms': 307320},
 {'title': 'ERE',
  'artist': 'Juan Karlos',
  'spotify_track_id': '2BLdelIp46CHvKkyWeqZHL',
  'spotify_url': 'https://open.spotify.com/track/2BLdelIp46CHvKkyWeqZHL',
  'album': 'Sad Songs and Bullshit Part 1',
  'image': 'https://i.scdn.co/image/ab67616d0000b27356b484a13efc1f2242a4dce8',
  'duration_ms': 284812},
 {'title': 'You Oughta Know',
  'artist': 'Alanis Morissette',
  'spotify_track_id': '3jS7bB0oXVOwGFZn3aE5NV',
  'spotify_url': 'https://open.spotify.com/track/3jS7bB0oXVOwGFZn3aE5NV',
  'album': 'Jagged Little Pill (2015 Remaster)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273242e643ea07118ecf677a6ef',
  'duration_ms': 249493},
 {'title': 'Cartier Gucci Scarf',
  'artist': 'Young Thug',
  'spotify_track_id': '3TWSar7EBNWZVeEWqDSjpw',
  'spotify_url': 'https://open.spotify.com/track/3TWSar7EBNWZVeEWqDSjpw',
  'album': 'So Much Fun',
  'image': 'https://i.scdn.co/image/ab67616d0000b2738da62aa4aa86bb58f67196e9',
  'duration_ms': 198173},
 {'title': 'Narda',
  'artist': 'Kamikazee',
  'spotify_track_id': '7pFoQ4rWKHaTUuoVCcIECH',
  'spotify_url': 'https://open.spotify.com/track/7pFoQ4rWKHaTUuoVCcIECH',
  'album': 'Maharot',
  'image': 'https://i.scdn.co/image/ab67616d0000b2732b8ce6fc2d59c87aafd6e157',
  'duration_ms': 284986},
 {'title': 'Halaga',
  'artist': 'Parokya ni Edgar',
  'spotify_track_id': '6Y1xjC0l259BVyZbk7iT4s',
  'spotify_url': 'https://open.spotify.com/track/6Y1xjC0l259BVyZbk7iT4s',
  'album': 'Gulong Itlog Gulong',
  'image': 'https://i.scdn.co/image/ab67616d0000b27387b7413135165919334c4577',
  'duration_ms': 352120},
 {'title': 'Tatsulok',
  'artist': 'Bamboo',
  'spotify_track_id': '2HM1cdgnKwuGTvmbxW9nJI',
  'spotify_url': 'https://open.spotify.com/track/2HM1cdgnKwuGTvmbxW9nJI',
  'album': 'Bamboo the Complete Hits',
  'image': 'https://i.scdn.co/image/ab67616d0000b27349a1d7493ca2912031da587d',
  'duration_ms': 253546},
 {'title': 'Fireflies',
  'artist': 'Owl City',
  'spotify_track_id': '3DamFFqW32WihKkTVlwTYQ',
  'spotify_url': 'https://open.spotify.com/track/3DamFFqW32WihKkTVlwTYQ',
  'album': 'Ocean Eyes',
  'image': 'https://i.scdn.co/image/ab67616d0000b273785d4e702802da500fc78b32',
  'duration_ms': 228346},
 {'title': 'I Will Survive',
  'artist': 'Demi Lovato',
  'spotify_track_id': '5pU2jicRzE4NAgXE7rOcKV',
  'spotify_url': 'https://open.spotify.com/track/5pU2jicRzE4NAgXE7rOcKV',
  'album': 'The Angry Birds Movie (Original Motion Picture Soundtrack)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273acd2af2b113e8b2ad2369af9',
  'duration_ms': 245986},
 {'title': 'Araw-Araw',
  'artist': 'Ben&Ben',
  'spotify_track_id': '4rG3h1QwgjSSWz8EIjCFrm',
  'spotify_url': 'https://open.spotify.com/track/4rG3h1QwgjSSWz8EIjCFrm',
  'album': 'LIMASAWA STREET',
  'image': 'https://i.scdn.co/image/ab67616d0000b273bbcb629ade1918ba09268794',
  'duration_ms': 313951},
 {'title': 'Kiss It Better',
  'artist': 'Rihanna',
  'spotify_track_id': '0UHB9METy4VCXNgkcGqHqS',
  'spotify_url': 'https://open.spotify.com/track/0UHB9METy4VCXNgkcGqHqS',
  'album': 'ANTI (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b2736be9bac15995f089579074de',
  'duration_ms': 253080},
 {'title': 'Dance All Night',
  'artist': 'ROSÉ',
  'spotify_track_id': '50aQbgfdydBXABx2gATQHn',
  'spotify_url': 'https://open.spotify.com/track/50aQbgfdydBXABx2gATQHn',
  'album': 'rosie',
  'image': 'https://i.scdn.co/image/ab67616d0000b2737be65ce6672ed7e5aac6e966',
  'duration_ms': 214950},
 {'title': 'Graduation March',
  'artist': 'Holiday Celebration Troupe',
  'spotify_track_id': '1uaFfBstndFSw4vntlb1k7',
  'spotify_url': 'https://open.spotify.com/track/1uaFfBstndFSw4vntlb1k7',
  'album': 'Here Comes the Bride: The Complete Wedding Collection',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734961643dd9c43d359e37c791',
  'duration_ms': 206293},
 {'title': 'Fight Song',
  'artist': 'Rachel Platten',
  'spotify_track_id': '37f4ITSlgPX81ad2EvmVQr',
  'spotify_url': 'https://open.spotify.com/track/37f4ITSlgPX81ad2EvmVQr',
  'album': 'Wildfire',
  'image': 'https://i.scdn.co/image/ab67616d0000b273a9e4d7fae5dfcc8f9cc96bc9',
  'duration_ms': 204013},
 {'title': 'Feels',
  'artist': 'Calvin Harris',
  'spotify_track_id': '5bcTCxgc7xVfSaMV3RuVke',
  'spotify_url': 'https://open.spotify.com/track/5bcTCxgc7xVfSaMV3RuVke',
  'album': 'Funk Wav Bounces Vol.1',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734d3fa5ce7ba599f4fd7803ef',
  'duration_ms': 223413},
 {'title': 'Hall of Fame',
  'artist': 'The Script ft. will.i.am',
  'spotify_track_id': '0FB5ILDICqwK6xj7W1RP9u',
  'spotify_url': 'https://open.spotify.com/track/0FB5ILDICqwK6xj7W1RP9u',
  'album': '#3 Deluxe Version',
  'image': 'https://i.scdn.co/image/ab67616d0000b2732e3049fef96abebf336b7366',
  'duration_ms': 201093},
 {'title': 'Believer',
  'artist': 'Imagine Dragons',
  'spotify_track_id': '0pqnGHJpmpxLKifKRmU6WP',
  'spotify_url': 'https://open.spotify.com/track/0pqnGHJpmpxLKifKRmU6WP',
  'album': 'Evolve',
  'image': 'https://i.scdn.co/image/ab67616d0000b2735675e83f707f1d7271e5cf8a',
  'duration_ms': 204346},
 {'title': 'Kathang Isip',
  'artist': 'Ben&Ben',
  'spotify_track_id': '3WUEs51GpcvlgU7lehLgLh',
  'spotify_url': 'https://open.spotify.com/track/3WUEs51GpcvlgU7lehLgLh',
  'album': 'Kathang Isip',
  'image': 'https://i.scdn.co/image/ab67616d0000b273bbf886276cd90f8d60b56a01',
  'duration_ms': 318814},
 {'title': 'Creep',
  'artist': 'Radiohead',
  'spotify_track_id': '70LcF31zb1H0PyJoS1Sx1r',
  'spotify_url': 'https://open.spotify.com/track/70LcF31zb1H0PyJoS1Sx1r',
  'album': 'Pablo Honey',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ec548c00d3ac2f10be73366d',
  'duration_ms': 238640},
 {'title': "Somebody's Watching Me",
  'artist': 'Rockwell',
  'spotify_track_id': '7jwQlYGpOml9ETGre1HqGA',
  'spotify_url': 'https://open.spotify.com/track/7jwQlYGpOml9ETGre1HqGA',
  'album': "Somebody's Watching Me",
  'image': 'https://i.scdn.co/image/ab67616d0000b27357de8cb9bbbe22a9e71c8af7',
  'duration_ms': 298866},
 {'title': 'No Surprises',
  'artist': 'Radiohead',
  'spotify_track_id': '10nyNJ6zNy2YVYLrcwLccB',
  'spotify_url': 'https://open.spotify.com/track/10nyNJ6zNy2YVYLrcwLccB',
  'album': 'OK Computer',
  'image': 'https://i.scdn.co/image/ab67616d0000b273c8b444df094279e70d0ed856',
  'duration_ms': 229120},
 {'title': 'Roar',
  'artist': 'Katy Perry',
  'spotify_track_id': '6F5c58TMEs1byxUstkzVeM',
  'spotify_url': 'https://open.spotify.com/track/6F5c58TMEs1byxUstkzVeM',
  'album': 'PRISM (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b27347f930accd8ac01686401fa2',
  'duration_ms': 223546},
 {'title': 'With a Smile',
  'artist': 'Eraserheads',
  'spotify_track_id': '1NopgVCMVhCKIm64tF7auX',
  'spotify_url': 'https://open.spotify.com/track/1NopgVCMVhCKIm64tF7auX',
  'album': 'Circus',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734ee9d148667165d546f88e84',
  'duration_ms': 278173},
 {'title': "I'm Scared",
  'artist': 'Young Thug',
  'spotify_track_id': '3uW1lWgdTN494vIxu3R9Or',
  'spotify_url': 'https://open.spotify.com/track/3uW1lWgdTN494vIxu3R9Or',
  'album': 'So Much Fun',
  'image': 'https://i.scdn.co/image/ab67616d0000b2738da62aa4aa86bb58f67196e9',
  'duration_ms': 200733},
 {'title': 'Battle Belongs',
  'artist': 'Phil Wickham',
  'spotify_track_id': '5pF1L2TboIEiZQwHekySET',
  'spotify_url': 'https://open.spotify.com/track/5pF1L2TboIEiZQwHekySET',
  'album': 'Hymn of Heaven',
  'image': 'https://i.scdn.co/image/ab67616d0000b2737c40908823a648108d4b8dac',
  'duration_ms': 287532},
 {'title': 'The Hills',
  'artist': 'The Weeknd',
  'spotify_track_id': '7fBv7CLKzipRk6EC6TWHOB',
  'spotify_url': 'https://open.spotify.com/track/7fBv7CLKzipRk6EC6TWHOB',
  'album': 'Beauty Behind The Madness',
  'image': 'https://i.scdn.co/image/ab67616d0000b2737fcead687e99583072cc217b',
  'duration_ms': 242253},
 {'title': 'Huwag Kang Matakot',
  'artist': 'Reese Lansangan',
  'spotify_track_id': '36CCCV4ha9PN4Oy7C6nRCE',
  'spotify_url': 'https://open.spotify.com/track/36CCCV4ha9PN4Oy7C6nRCE',
  'album': 'Pop Machine: Huwag Kang Matakot',
  'image': 'https://i.scdn.co/image/ab67616d0000b27309534a23c570a20bd7af790c',
  'duration_ms': 238179},
 {'title': 'Leaves',
  'artist': 'Ben&Ben',
  'spotify_track_id': '6wdCelHrPh7UfliNjwRTUv',
  'spotify_url': 'https://open.spotify.com/track/6wdCelHrPh7UfliNjwRTUv',
  'album': 'Leaves',
  'image': 'https://i.scdn.co/image/ab67616d0000b273189948156c1fadd99af89f50',
  'duration_ms': 310708},
 {'title': 'Somebody Else',
  'artist': 'The 1975',
  'spotify_track_id': '4m0q0xQ2BNl9SCAGKyfiGZ',
  'spotify_url': 'https://open.spotify.com/track/4m0q0xQ2BNl9SCAGKyfiGZ',
  'album': 'I like it when you sleep, for you are so beautiful yet so unaware of it',
  'image': 'https://i.scdn.co/image/ab67616d0000b273206517a3f7e4c34bf0bfc531',
  'duration_ms': 347525},
 {'title': '505',
  'artist': 'Arctic Monkeys',
  'spotify_track_id': '0BxE4FqsDD1Ot4YuBXwAPp',
  'spotify_url': 'https://open.spotify.com/track/0BxE4FqsDD1Ot4YuBXwAPp',
  'album': 'Favourite Worst Nightmare',
  'image': 'https://i.scdn.co/image/ab67616d0000b273b1f8da74f225fa1225cdface',
  'duration_ms': 253586},
 {'title': 'Pahinga',
  'artist': 'Ben&Ben',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'From the Start',
  'artist': 'Laufey',
  'spotify_track_id': '43iIQbw5hx986dUEZbr3eN',
  'spotify_url': 'https://open.spotify.com/track/43iIQbw5hx986dUEZbr3eN',
  'album': 'Bewitched',
  'image': 'https://i.scdn.co/image/ab67616d0000b27374c732f8aa0e0ccbb3d17d96',
  'duration_ms': 169573},
 {'title': 'Valentine',
  'artist': 'Laufey',
  'spotify_track_id': '6cx5CvFhqN19efStehJqoW',
  'spotify_url': 'https://open.spotify.com/track/6cx5CvFhqN19efStehJqoW',
  'album': 'Everything I Know About Love',
  'image': 'https://i.scdn.co/image/ab67616d0000b27348341e864d4b4881f56f01b4',
  'duration_ms': 168906},
 {'title': '1-800-273-8255',
  'artist': 'Logic ft. Alessia Cara & Khalid',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Dati',
  'artist': 'Sam Concepcion',
  'spotify_track_id': '6IMiW1ZynVwShkCiuB9wkQ',
  'spotify_url': 'https://open.spotify.com/track/6IMiW1ZynVwShkCiuB9wkQ',
  'album': 'Philpop 2013',
  'image': 'https://i.scdn.co/image/ab67616d0000b27362958f881ae10afae656b253',
  'duration_ms': 240600},
 {'title': 'Memories',
  'artist': 'Maroon 5',
  'spotify_track_id': '4cktbXiXOapiLBMprHFErI',
  'spotify_url': 'https://open.spotify.com/track/4cktbXiXOapiLBMprHFErI',
  'album': 'JORDI (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b27386a8ab515de4b7aef28cd631',
  'duration_ms': 189486},
 {'title': 'Photograph',
  'artist': 'Ed Sheeran',
  'spotify_track_id': '1HNkqx9Ahdgi1Ixy2xkKkL',
  'spotify_url': 'https://open.spotify.com/track/1HNkqx9Ahdgi1Ixy2xkKkL',
  'album': 'x (Deluxe Edition)',
  'image': 'https://i.scdn.co/image/ab67616d0000b27313b3e37318a0c247b550bccd',
  'duration_ms': 258986},
 {'title': 'Every Woman in the World',
  'artist': 'Air Supply',
  'spotify_track_id': '3QVF04HFQTAXWcVVB8YrCU',
  'spotify_url': 'https://open.spotify.com/track/3QVF04HFQTAXWcVVB8YrCU',
  'album': 'Greatest Hits',
  'image': 'https://i.scdn.co/image/ab67616d0000b273a07d5489dbdf03aa31a37ee4',
  'duration_ms': 209066},
 {'title': 'Ang Huling El Bimbo',
  'artist': 'Eraserheads',
  'spotify_track_id': '135ggzbjOogZ75IQ0LQi8r',
  'spotify_url': 'https://open.spotify.com/track/135ggzbjOogZ75IQ0LQi8r',
  'album': 'Cutterpillow',
  'image': 'https://i.scdn.co/image/ab67616d0000b2739bacd20b2fad742126a482e1',
  'duration_ms': 447333},
 {'title': '7 Years',
  'artist': 'Lukas Graham',
  'spotify_track_id': '5kqIPrATaCc2LqxVWzQGbk',
  'spotify_url': 'https://open.spotify.com/track/5kqIPrATaCc2LqxVWzQGbk',
  'album': 'Lukas Graham',
  'image': 'https://i.scdn.co/image/ab67616d0000b2732d94d0f04e9a58d1654b760b',
  'duration_ms': 237300},
 {'title': 'Perfect',
  'artist': 'Ed Sheeran',
  'spotify_track_id': '0tgVpDi06FyKpA1z0VMD4v',
  'spotify_url': 'https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v',
  'album': '÷ (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96',
  'duration_ms': 263400},
 {'title': 'Everybody Wants to Rule the World',
  'artist': 'Tears for Fears',
  'spotify_track_id': '4RvWPyQ5RL0ao9LPZeSouE',
  'spotify_url': 'https://open.spotify.com/track/4RvWPyQ5RL0ao9LPZeSouE',
  'album': 'Songs From The Big Chair (Super Deluxe Edition)',
  'image': 'https://i.scdn.co/image/ab67616d0000b27322463d6939fec9e17b2a6235',
  'duration_ms': 251488},
 {'title': 'Misteryoso',
  'artist': 'Cup of Joe',
  'spotify_track_id': '0kE1SmlJNLg14dgdo9kJws',
  'spotify_url': 'https://open.spotify.com/track/0kE1SmlJNLg14dgdo9kJws',
  'album': 'Misteryoso',
  'image': 'https://i.scdn.co/image/ab67616d0000b273802c8fee6eb6692b08b204a4',
  'duration_ms': 221641},
 {'title': 'Bibingka',
  'artist': 'Ben&Ben',
  'spotify_track_id': '3nmRSlzR7xtAo95GjfIahZ',
  'spotify_url': 'https://open.spotify.com/track/3nmRSlzR7xtAo95GjfIahZ',
  'album': 'Pintig Ng Pasko',
  'image': 'https://i.scdn.co/image/ab67616d0000b273047aeaec4ba570e26f249160',
  'duration_ms': 306066},
 {'title': 'Chest Pain',
  'artist': 'Malcolm Todd',
  'spotify_track_id': '3gPYoFtn70aTgl546XVSET',
  'spotify_url': 'https://open.spotify.com/track/3gPYoFtn70aTgl546XVSET',
  'album': 'Chest Pain (I Love)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273c4b4ad9943cf308e464f7a3c',
  'duration_ms': 200826},
 {'title': 'A Thousand Years',
  'artist': 'Christina Perri',
  'spotify_track_id': '6lanRgr6wXibZr8KgzXxBl',
  'spotify_url': 'https://open.spotify.com/track/6lanRgr6wXibZr8KgzXxBl',
  'album': 'a thousand years',
  'image': 'https://i.scdn.co/image/ab67616d0000b2733dea4a2ccd58ad1f8e4dbb03',
  'duration_ms': 285120},
 {'title': 'On Bended Knee',
  'artist': 'Boyz II Men',
  'spotify_track_id': '4Gmkqn3V7IMTkOmmiX7cbb',
  'spotify_url': 'https://open.spotify.com/track/4Gmkqn3V7IMTkOmmiX7cbb',
  'album': 'II',
  'image': 'https://i.scdn.co/image/ab67616d0000b273a94a1672a1fc0373b3e9aa7b',
  'duration_ms': 329800},
 {'title': "Can't Help Falling in Love",
  'artist': 'Elvis Presley',
  'spotify_track_id': '44AyOl4qVkzS48vBsbNXaC',
  'spotify_url': 'https://open.spotify.com/track/44AyOl4qVkzS48vBsbNXaC',
  'album': 'Blue Hawaii',
  'image': 'https://i.scdn.co/image/ab67616d0000b273b184226408f981e3dd17c606',
  'duration_ms': 185877},
 {'title': 'All of Me',
  'artist': 'John Legend',
  'spotify_track_id': '3U4isOIWM3VvDubwSI3y7a',
  'spotify_url': 'https://open.spotify.com/track/3U4isOIWM3VvDubwSI3y7a',
  'album': 'Love In The Future (Expanded Edition)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273bdcc3b587b5249932bc415c2',
  'duration_ms': 269556},
 {'title': 'Fill It',
  'artist': 'Young Thug',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Iris',
  'artist': 'Goo Goo Dolls',
  'spotify_track_id': '2eoMrFVXnuLSDrHReeqpIz',
  'spotify_url': 'https://open.spotify.com/track/2eoMrFVXnuLSDrHReeqpIz',
  'album': 'Romantic Songs',
  'image': 'https://i.scdn.co/image/ab67616d0000b273c3559d526922b41d9e5720e2',
  'duration_ms': 289906},
 {'title': 'So Sick',
  'artist': 'Ne-Yo',
  'spotify_track_id': '6brl7bwOHmGFkNw3MBqssT',
  'spotify_url': 'https://open.spotify.com/track/6brl7bwOHmGFkNw3MBqssT',
  'album': 'In My Own Words',
  'image': 'https://i.scdn.co/image/ab67616d0000b273987a1825341694ec9bc62457',
  'duration_ms': 207186},
 {'title': 'All by Myself',
  'artist': 'Celine Dion',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Always',
  'artist': 'Daniel Caesar',
  'spotify_track_id': '2LlOeW5rVcvl3QcPNPcDus',
  'spotify_url': 'https://open.spotify.com/track/2LlOeW5rVcvl3QcPNPcDus',
  'album': 'NEVER ENOUGH',
  'image': 'https://i.scdn.co/image/ab67616d0000b2737c68face1dc58127f3a7b1cc',
  'duration_ms': 225312},
 {'title': 'Lonely',
  'artist': 'Justin Bieber & benny blanco',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Raining in Manila',
  'artist': 'Lola Amour',
  'spotify_track_id': '0mtkRIAOueeXqHpyahIbtJ',
  'spotify_url': 'https://open.spotify.com/track/0mtkRIAOueeXqHpyahIbtJ',
  'album': 'Raining In Manila',
  'image': 'https://i.scdn.co/image/ab67616d0000b2739719f85e9d866aaa9a32fe28',
  'duration_ms': 291070},
 {'title': 'Dancing on My Own',
  'artist': 'Robyn',
  'spotify_track_id': '6aqNCrRA7vs7v6QvRpI50t',
  'spotify_url': 'https://open.spotify.com/track/6aqNCrRA7vs7v6QvRpI50t',
  'album': 'Body Talk',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734689597708c1b0b3dcb9ecaf',
  'duration_ms': 285853},
 {'title': 'Sana',
  'artist': 'I Belong to the Zoo',
  'spotify_track_id': '3fnErhPtcoP2xz4hFfZpLZ',
  'spotify_url': 'https://open.spotify.com/track/3fnErhPtcoP2xz4hFfZpLZ',
  'album': 'Kapiling',
  'image': 'https://i.scdn.co/image/ab67616d0000b2735d8214dd18e5439c63e985ee',
  'duration_ms': 272564},
 {'title': "Kahit 'Di Mo Alam",
  'artist': 'South Border',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Weston Road Flows',
  'artist': 'Drake',
  'spotify_track_id': '4PA16FAl8LPmFmOhARawdV',
  'spotify_url': 'https://open.spotify.com/track/4PA16FAl8LPmFmOhARawdV',
  'album': 'Views',
  'image': 'https://i.scdn.co/image/ab67616d0000b2739416ed64daf84936d89e671c',
  'duration_ms': 253533},
 {'title': 'The A Team',
  'artist': 'Ed Sheeran',
  'spotify_track_id': '1VdZ0vKfR5jneCmWIUAMxK',
  'spotify_url': 'https://open.spotify.com/track/1VdZ0vKfR5jneCmWIUAMxK',
  'album': '+',
  'image': 'https://i.scdn.co/image/ab67616d0000b273e6d489d359c546fea254f440',
  'duration_ms': 258373},
 {'title': 'Seasons',
  'artist': 'wave to earth',
  'spotify_track_id': '0aVd7QiY8BstysHb62c5Fi',
  'spotify_url': 'https://open.spotify.com/track/0aVd7QiY8BstysHb62c5Fi',
  'album': 'summer flows 0.02',
  'image': 'https://i.scdn.co/image/ab67616d0000b2733b975ed7ccd57f3a00d570cf',
  'duration_ms': 256000},
 {'title': 'Ocean Eyes',
  'artist': 'Billie Eilish',
  'spotify_track_id': '2uIX8YMNjGMD7441kqyyNU',
  'spotify_url': 'https://open.spotify.com/track/2uIX8YMNjGMD7441kqyyNU',
  'album': 'Ocean Eyes',
  'image': 'https://i.scdn.co/image/ab67616d0000b2732cafcdd985630d72594ecc49',
  'duration_ms': 200560},
 {'title': 'Best Friend',
  'artist': 'Rex Orange County',
  'spotify_track_id': '3rPtS4nfpy7PsARctAWpzd',
  'spotify_url': 'https://open.spotify.com/track/3rPtS4nfpy7PsARctAWpzd',
  'album': 'Best Friend',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ff874602e13e9181c26e5f01',
  'duration_ms': 262231},
 {'title': 'Weightless',
  'artist': 'Marconi Union',
  'spotify_track_id': '6kkwzB6hXLIONkEk9JciA6',
  'spotify_url': 'https://open.spotify.com/track/6kkwzB6hXLIONkEk9JciA6',
  'album': 'The Ambient Zone Just Music Cafe Vol 4',
  'image': 'https://i.scdn.co/image/ab67616d0000b273f399efa20097105e9db88560',
  'duration_ms': 480106},
 {'title': 'Merry-Go-Round',
  'artist': 'Joe Hisaishi',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Bleeding Love',
  'artist': 'Leona Lewis',
  'spotify_track_id': '7wZUrN8oemZfsEd1CGkbXE',
  'spotify_url': 'https://open.spotify.com/track/7wZUrN8oemZfsEd1CGkbXE',
  'album': 'Spirit',
  'image': 'https://i.scdn.co/image/ab67616d0000b27334fd9eb8cd48e518598aec55',
  'duration_ms': 262466},
 {'title': 'River Flows in You',
  'artist': 'Yiruma',
  'spotify_track_id': '2agBDIr9MYDUducQPC1sFU',
  'spotify_url': 'https://open.spotify.com/track/2agBDIr9MYDUducQPC1sFU',
  'album': 'First Love (The Original & the Very First Recording)',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734bdb66d1335f8571240e755f',
  'duration_ms': 188786},
 {'title': 'Bawat Daan',
  'artist': 'Ebe Dancel',
  'spotify_track_id': '1hJtJvPX9knMysNDQw0HDJ',
  'spotify_url': 'https://open.spotify.com/track/1hJtJvPX9knMysNDQw0HDJ',
  'album': 'Bawat Daan',
  'image': 'https://i.scdn.co/image/ab67616d0000b273f600a0a2669e7c2044986752',
  'duration_ms': 300240},
 {'title': 'Under Pressure',
  'artist': 'Queen & David Bowie',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'We Belong Together',
  'artist': 'Mariah Carey',
  'spotify_track_id': '4EI8VuxUuIHKfafU72emqz',
  'spotify_url': 'https://open.spotify.com/track/4EI8VuxUuIHKfafU72emqz',
  'album': 'The Emancipation of Mimi',
  'image': 'https://i.scdn.co/image/ab67616d0000b273006adc0cc250c8f9c5494aec',
  'duration_ms': 201400},
 {'title': 'Night Dancer',
  'artist': 'imase',
  'spotify_track_id': '348NF6vX0Yh22xvH0EZEro',
  'spotify_url': 'https://open.spotify.com/track/348NF6vX0Yh22xvH0EZEro',
  'album': 'NIGHT DANCER',
  'image': 'https://i.scdn.co/image/ab67616d0000b273e2a3788f1a9dea9028099d4e',
  'duration_ms': 210948},
 {'title': 'Pressure',
  'artist': 'Paramore',
  'spotify_track_id': '7mG2RbhyzGsjpQOz568d39',
  'spotify_url': 'https://open.spotify.com/track/7mG2RbhyzGsjpQOz568d39',
  'album': 'All We Know Is Falling',
  'image': 'https://i.scdn.co/image/ab67616d0000b2735cab62839794c2cc3d6a135b',
  'duration_ms': 185733},
 {'title': 'Stressed Out',
  'artist': 'Twenty One Pilots',
  'spotify_track_id': '3CRDbSIZ4r5MsZ0YwxuEkn',
  'spotify_url': 'https://open.spotify.com/track/3CRDbSIZ4r5MsZ0YwxuEkn',
  'album': 'Blurryface',
  'image': 'https://i.scdn.co/image/ab67616d0000b2732df0d98a423025032d0db1f7',
  'duration_ms': 202333},
 {'title': 'Hallelujah',
  'artist': 'Boyce Avenue',
  'spotify_track_id': '5D6xoqZwDoqRO5V9rNgxFO',
  'spotify_url': 'https://open.spotify.com/track/5D6xoqZwDoqRO5V9rNgxFO',
  'album': 'Cover Sessions, Vol. 6',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ace4d9ab4b163d047af84d34',
  'duration_ms': 267765},
 {'title': 'No One Noticed',
  'artist': 'The Marías',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'This Side of Paradise',
  'artist': 'Coyote Theory',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Bang Bang',
  'artist': 'Jessie J, Ariana Grande & Nicki Minaj',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Wake Me Up',
  'artist': 'Avicii',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Versace on the Floor',
  'artist': 'Bruno Mars',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'All I Do Is Win',
  'artist': 'DJ Khaled',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Surprise Yourself',
  'artist': 'Jack Garratt',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Dynamite',
  'artist': 'BTS',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': "I'm Nilalangam",
  'artist': 'Cesca',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Ilaw sa Daan',
  'artist': 'IV of Spades',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Swiss Beats',
  'artist': 'Young Thug',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Happier',
  'artist': 'Marshmello & Bastill',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'The Day You Said Goodnight',
  'artist': 'Hale',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Kahit Ayaw Mo Na',
  'artist': 'This Band',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0},
 {'title': 'Pasilyo',
  'artist': 'SunKissed Lola',
  'spotify_track_id': '0uZFcsx96wzbixsULmrg8o',
  'spotify_url': 'https://open.spotify.com/track/0uZFcsx96wzbixsULmrg8o',
  'album': 'Pasilyo',
  'image': 'https://i.scdn.co/image/ab67616d0000b2734978596b32fde00ce5c4d07d',
  'duration_ms': 270250},
 {'title': 'Castle on the Hill',
  'artist': 'Ed Sheeran',
  'spotify_track_id': '6PCUP3dWmTjcTtXY02oFdT',
  'spotify_url': 'https://open.spotify.com/track/6PCUP3dWmTjcTtXY02oFdT',
  'album': '÷ (Deluxe)',
  'image': 'https://i.scdn.co/image/ab67616d0000b273ba5db46f4b838ef6027e6f96',
  'duration_ms': 261153},
 {'title': 'Whatever It Takes',
  'artist': 'Imagine Dragons',
  'spotify_track_id': None,
  'spotify_url': None,
  'album': '',
  'image': '',
  'duration_ms': 0}]

# (emotion, position, title, artist)
LINKS = [('happy', 1, 'Happy', 'Pharrell Williams'),
 ('happy', 2, "Can't Stop the Feeling!", 'Justin Timberlake'),
 ('happy', 3, 'Best Day of My Life', 'American Authors'),
 ('happy', 4, 'Shake It Off', 'Taylor Swift'),
 ('happy', 5, 'Favorite Rings', 'Taylor Swift'),
 ('happy', 6, 'Salamin-Salamin', 'BINI'),
 ('happy', 7, 'Awitin Mo at Isasayaw Ko', 'VST & Company'),
 ('happy', 8, 'Walking on Sunshine', 'Katrina and the Waves'),
 ('happy', 9, "Don't Stop Me Now", 'Queen'),
 ('happy', 10, 'Ligaya', 'Eraserheads'),
 ('sad', 1, 'Fix You', 'Coldplay'),
 ('sad', 2, 'Before It Sinks In', 'Moira Dela Torre'),
 ('sad', 3, 'Happier', 'Ed Sheeran'),
 ('sad', 4, 'The Night We Met', 'Lord Huron'),
 ('sad', 5, '12:51', 'Krissy & Ericka'),
 ('sad', 6, 'Huling Sandali', 'December Avenue'),
 ('sad', 7, "You'll Be in My Heart", 'NIKI'),
 ('sad', 8, 'Let Her Go', 'Passenger'),
 ('sad', 9, 'Blue', 'Yung Kai'),
 ('angry', 1, '21 Guns', 'Green Day'),
 ('angry', 2, 'Look What You Made Me Do', 'Taylor Swift'),
 ('angry', 3, 'Nosi Ba Lasi', 'Sampaguita'),
 ('angry', 4, 'Cool Off', 'Yeng Constantino'),
 ('angry', 5, 'ERE', 'Juan Karlos'),
 ('angry', 6, 'You Oughta Know', 'Alanis Morissette'),
 ('angry', 7, 'Cartier Gucci Scarf', 'Young Thug'),
 ('angry', 8, 'Narda', 'Kamikazee'),
 ('angry', 9, 'Halaga', 'Parokya ni Edgar'),
 ('angry', 10, 'Tatsulok', 'Bamboo'),
 ('motivational', 1, 'Fireflies', 'Owl City'),
 ('motivational', 2, 'I Will Survive', 'Demi Lovato'),
 ('motivational', 3, 'Araw-Araw', 'Ben&Ben'),
 ('motivational', 4, 'Kiss It Better', 'Rihanna'),
 ('motivational', 5, 'Dance All Night', 'ROSÉ'),
 ('motivational', 6, 'Graduation March', 'Holiday Celebration Troupe'),
 ('motivational', 7, 'Fight Song', 'Rachel Platten'),
 ('motivational', 8, 'Feels', 'Calvin Harris'),
 ('motivational', 9, 'Hall of Fame', 'The Script ft. will.i.am'),
 ('motivational', 10, 'Believer', 'Imagine Dragons'),
 ('fear', 1, 'Kathang Isip', 'Ben&Ben'),
 ('fear', 2, 'Creep', 'Radiohead'),
 ('fear', 3, "Somebody's Watching Me", 'Rockwell'),
 ('fear', 4, 'No Surprises', 'Radiohead'),
 ('fear', 5, 'Roar', 'Katy Perry'),
 ('fear', 6, 'With a Smile', 'Eraserheads'),
 ('fear', 7, "I'm Scared", 'Young Thug'),
 ('fear', 8, 'Battle Belongs', 'Phil Wickham'),
 ('fear', 9, 'The Hills', 'The Weeknd'),
 ('fear', 10, 'Huwag Kang Matakot', 'Reese Lansangan'),
 ('depressing', 1, 'Fix You', 'Coldplay'),
 ('depressing', 2, 'Leaves', 'Ben&Ben'),
 ('depressing', 3, 'Somebody Else', 'The 1975'),
 ('depressing', 4, '505', 'Arctic Monkeys'),
 ('depressing', 5, 'Pahinga', 'Ben&Ben'),
 ('depressing', 6, 'From the Start', 'Laufey'),
 ('depressing', 7, 'Valentine', 'Laufey'),
 ('depressing', 8, 'With a Smile', 'Eraserheads'),
 ('depressing', 9, '1-800-273-8255', 'Logic ft. Alessia Cara & Khalid'),
 ('nostalgic', 1, 'Dati', 'Sam Concepcion'),
 ('nostalgic', 2, 'Memories', 'Maroon 5'),
 ('nostalgic', 3, 'Photograph', 'Ed Sheeran'),
 ('nostalgic', 4, 'Every Woman in the World', 'Air Supply'),
 ('nostalgic', 5, 'Ang Huling El Bimbo', 'Eraserheads'),
 ('nostalgic', 6, '7 Years', 'Lukas Graham'),
 ('nostalgic', 7, 'Perfect', 'Ed Sheeran'),
 ('nostalgic', 8, 'Fireflies', 'Owl City'),
 ('nostalgic', 9, 'Everybody Wants to Rule the World', 'Tears for Fears'),
 ('romantic', 1, 'Perfect', 'Ed Sheeran'),
 ('romantic', 2, 'Photograph', 'Ed Sheeran'),
 ('romantic', 3, 'Misteryoso', 'Cup of Joe'),
 ('romantic', 4, 'Bibingka', 'Ben&Ben'),
 ('romantic', 5, 'Chest Pain', 'Malcolm Todd'),
 ('romantic', 6, 'A Thousand Years', 'Christina Perri'),
 ('romantic', 7, 'On Bended Knee', 'Boyz II Men'),
 ('romantic', 8, 'Blue', 'Yung Kai'),
 ('romantic', 9, "Can't Help Falling in Love", 'Elvis Presley'),
 ('romantic', 10, 'All of Me', 'John Legend'),
 ('romantic', 11, 'Fill It', 'Young Thug'),
 ('lonely', 1, 'Iris', 'Goo Goo Dolls'),
 ('lonely', 2, 'So Sick', 'Ne-Yo'),
 ('lonely', 3, 'All by Myself', 'Celine Dion'),
 ('lonely', 4, 'Always', 'Daniel Caesar'),
 ('lonely', 5, 'Lonely', 'Justin Bieber & benny blanco'),
 ('lonely', 6, 'Raining in Manila', 'Lola Amour'),
 ('lonely', 7, 'Dancing on My Own', 'Robyn'),
 ('lonely', 8, 'Sana', 'I Belong to the Zoo'),
 ('lonely', 9, "Kahit 'Di Mo Alam", 'South Border'),
 ('lonely', 10, 'Weston Road Flows', 'Drake'),
 ('lonely', 11, 'The A Team', 'Ed Sheeran'),
 ('calm', 1, 'Blue', 'Yung Kai'),
 ('calm', 2, 'Seasons', 'wave to earth'),
 ('calm', 3, 'Ocean Eyes', 'Billie Eilish'),
 ('calm', 4, 'Best Friend', 'Rex Orange County'),
 ('calm', 5, 'Weightless', 'Marconi Union'),
 ('calm', 6, 'Merry-Go-Round', 'Joe Hisaishi'),
 ('calm', 7, 'Leaves', 'Ben&Ben'),
 ('calm', 8, 'Bleeding Love', 'Leona Lewis'),
 ('calm', 9, 'River Flows in You', 'Yiruma'),
 ('calm', 10, 'Bawat Daan', 'Ebe Dancel'),
 ('stressed', 1, 'Under Pressure', 'Queen & David Bowie'),
 ('stressed', 2, 'We Belong Together', 'Mariah Carey'),
 ('stressed', 3, 'Araw-Araw', 'Ben&Ben'),
 ('stressed', 4, 'Leaves', 'Ben&Ben'),
 ('stressed', 5, 'Night Dancer', 'imase'),
 ('stressed', 6, 'Pressure', 'Paramore'),
 ('stressed', 7, 'Stressed Out', 'Twenty One Pilots'),
 ('stressed', 8, 'Hallelujah', 'Boyce Avenue'),
 ('stressed', 9, 'No One Noticed', 'The Marías'),
 ('stressed', 10, 'This Side of Paradise', 'Coyote Theory'),
 ('surprising', 1, 'Bang Bang', 'Jessie J, Ariana Grande & Nicki Minaj'),
 ('surprising', 2, 'Misteryoso', 'Cup of Joe'),
 ('surprising', 3, 'Wake Me Up', 'Avicii'),
 ('surprising', 4, 'Versace on the Floor', 'Bruno Mars'),
 ('surprising', 5, 'All I Do Is Win', 'DJ Khaled'),
 ('surprising', 6, 'Surprise Yourself', 'Jack Garratt'),
 ('surprising', 7, 'Dynamite', 'BTS'),
 ('surprising', 8, "I'm Nilalangam", 'Cesca'),
 ('surprising', 9, 'Ilaw sa Daan', 'IV of Spades'),
 ('surprising', 10, 'Swiss Beats', 'Young Thug'),
 ('mixed', 1, 'Happier', 'Marshmello & Bastill'),
 ('mixed', 2, 'The Day You Said Goodnight', 'Hale'),
 ('mixed', 3, 'Kahit Ayaw Mo Na', 'This Band'),
 ('mixed', 4, 'Pasilyo', 'SunKissed Lola'),
 ('mixed', 5, 'Castle on the Hill', 'Ed Sheeran'),
 ('mixed', 6, 'Whatever It Takes', 'Imagine Dragons')]


def seed(apps, schema_editor):
    Emotion = apps.get_model('api', 'Emotion')
    Song = apps.get_model('api', 'Song')
    EmotionSong = apps.get_model('api', 'EmotionSong')

    emotions = {
        name: Emotion.objects.update_or_create(name=name, defaults={'display_name': display})[0]
        for name, display in EMOTIONS
    }
    songs = {}
    for row in SONGS:
        song, _ = Song.objects.update_or_create(
            title=row['title'],
            artist=row['artist'],
            defaults={key: value for key, value in row.items() if key not in ('title', 'artist')},
        )
        songs[(row['title'], row['artist'])] = song
    for emotion, position, title, artist in LINKS:
        EmotionSong.objects.update_or_create(
            emotion=emotions[emotion],
            song=songs[(title, artist)],
            defaults={'position': position},
        )


def unseed(apps, schema_editor):
    apps.get_model('api', 'EmotionSong').objects.all().delete()
    apps.get_model('api', 'Song').objects.all().delete()
    apps.get_model('api', 'Emotion').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_therapist_song_collection'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
