# Generated by Django 4.2.13 on 2026-09-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_terms_and_personalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritetrack',
            name='emotion',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('motivational', 'Motivational'), ('fear', 'Fear'), ('depressing', 'Depressing'), ('surprising', 'Surprising'), ('stressed', 'Stressed'), ('calm', 'Calm'), ('lonely', 'Lonely'), ('romantic', 'Romantic'), ('nostalgic', 'Nostalgic'), ('mixed', 'Mixed')], db_index=True, default='', max_length=50),
        ),
    ]
