# Generated by Django 4.2.13 on 2026-10-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_username_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personalization_opt_in',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
