# Generated by Django 4.2.13 on 2026-10-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_personalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_artists',
        ),
    ]
